### ISSUE TITLE
Some lookups fail. Dockerized dnsmasq unusable.

### ISSUE THREAD

**Issue by adrianharabula** [4km3/docker-dnsmasq#22] opened 2018-12-28 17:23 UTC
Hello,

I'm using Docker 18.09.0. Tried the 2.75, 2.78 and latest dnsmasq docker images.

I start the service with:
```
docker run --restart=always --name=dnsmasq -d -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN andyshinn/dnsmasq:2.75 --server=1.1.1.1
```

On the host machine, if I hit repeatedly
```
nslookup google.com
```
Some queries get stuck for some seconds. In browser this is seen as pages unable to load until I hit refresh. It renders the dns server unusable.

Using dnsmasq binary directly on host does not have this problem.

**Comment by andyshinn** [comment] 2020-08-16 22:03
I can't reproduce this. I just tried locally and works for me:

```
docker-dnsmasq on  master took 3s 
❯ docker run --restart=always --name=dnsmasq -d -p 53:53/tcp -p 53:53/udp --cap-add=NET_ADMIN andyshinn/dnsmasq:2.75 --server=1.1.1.1
Unable to find image 'andyshinn/dnsmasq:2.75' locally
2.75: Pulling from andyshinn/dnsmasq
Image docker.io/andyshinn/dnsmasq:2.75 uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
8f4ec95ceaee: Pull complete 
586c97d70323: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:df2e825107e3f762ad3db5a886a4eebf78b873463ed097bb4f792f1c321c2fc5
Status: Downloaded newer image for andyshinn/dnsmasq:2.75
4fcda54beab203607f9240599bff2917833b8cf3352873aa1d5a1036a699fbec

docker-dnsmasq on  master 
❯ dig @127.0.0.1 +noall +answer google.com
google.com.		99	IN	A	172.217.14.174

docker-dnsmasq on  master 
❯ docker stop dnsmasq                  
dnsmasq

docker-dnsmasq on  master 
❯ dig @127.0.0.1 +noall +answer google.com
;; connection timed out; no servers could be reached
```
Any logs from the container? I'm going to close this since it is pretty old. But feel free to reopen if it's still a problem.

**Closed as completed by andyshinn** 2020-08-16 22:03 UTC
